// SPDX-License-Identifier: MPL-2.0

// Codegen + bundle orchestrator for WebExtension actors.
//
// For each <name>/actor.ts it generates a privileged built-in WebExtension into
// _dist/<name>/: manifest.json, schema.json, api.js (experiment parent), and
// background.js are generated text; actor.mjs (parent methods) and content.js
// (content hook + runtime + birpc) are bundled by tsdown.
//
// The actor module's top level must be pure: this script imports it under Deno
// to read `meta` and the parent method names, so it must not touch Firefox
// globals (Services, ChromeUtils, window, ...) outside of method/hook bodies.

import * as path from "@std/path";

const ROOT = path.dirname(path.fromFileUrl(import.meta.url));
const DIST = path.join(ROOT, "_dist");
const GEN = path.join(ROOT, "_gen");

const mode =
  Deno.args
    .find((a) => a.startsWith("--env.MODE="))
    ?.slice("--env.MODE=".length) ?? "dev";

interface ActorMeta {
  id: string;
  version: string;
  namespace: string;
  matches: string[];
  runAt?: string;
}

interface Actor {
  dir: string;
  meta: ActorMeta;
  methods: Array<{ name: string; arity: number }>;
}

function discoverActorDirs(): string[] {
  const dirs: string[] = [];
  for (const entry of Deno.readDirSync(ROOT)) {
    if (!entry.isDirectory) continue;
    if (entry.name.startsWith("_") || entry.name === "node_modules") continue;
    try {
      Deno.statSync(path.join(ROOT, entry.name, "actor.ts"));
      dirs.push(entry.name);
    } catch {
      // no actor.ts here
    }
  }
  return dirs.sort();
}

async function loadActor(dir: string): Promise<Actor> {
  const mod = await import(
    path.toFileUrl(path.join(ROOT, dir, "actor.ts")).href
  );
  const meta = mod.meta as ActorMeta;
  const parent = mod.parent as Record<string, (...a: unknown[]) => unknown>;
  const methods = Object.keys(parent).map((name) => ({
    name,
    arity: parent[name].length,
  }));
  return { dir, meta, methods };
}

function genManifest(a: Actor): string {
  const manifest = {
    manifest_version: 2,
    name: a.dir,
    version: a.meta.version,
    browser_specific_settings: { gecko: { id: a.meta.id } },
    hidden: true,
    permissions: ["mozillaAddons"],
    background: { scripts: ["background.js"] },
    content_scripts: [
      {
        matches: a.meta.matches,
        js: ["content.js"],
        run_at: a.meta.runAt ?? "document_end",
        all_frames: false,
      },
    ],
    experiment_apis: {
      [a.meta.namespace]: {
        schema: "schema.json",
        parent: {
          scopes: ["addon_parent"],
          script: "api.js",
          paths: [[a.meta.namespace]],
        },
      },
    },
  };
  return JSON.stringify(manifest, null, 2) + "\n";
}

function genSchema(a: Actor): string {
  const functions = a.methods.map((m) => ({
    name: m.name,
    type: "function",
    async: true,
    parameters: Array.from({ length: m.arity }, (_, i) => ({
      name: `arg${i}`,
      type: "any",
    })),
  }));
  return (
    JSON.stringify(
      [{ namespace: a.meta.namespace, functions }],
      null,
      2,
    ) + "\n"
  );
}

function genApi(a: Actor): string {
  const ns = a.meta.namespace;
  return `// SPDX-License-Identifier: MPL-2.0
// GENERATED by build.ts. Edit ${a.dir}/actor.ts instead.

/* global ExtensionAPI, ChromeUtils */

"use strict";

this.${ns} = class extends ExtensionAPI {
  getAPI() {
    const { parent } = ChromeUtils.importESModule(
      "resource://noraneko-builtin/${a.dir}/actor.mjs",
    );
    return { ${ns}: parent };
  }
};
`;
}

function genBackground(a: Actor): string {
  const ns = a.meta.namespace;
  const methods = a.methods.map((m) => `"${m.name}"`).join(", ");
  return `// SPDX-License-Identifier: MPL-2.0
// GENERATED by build.ts. Edit ${a.dir}/actor.ts instead.

/* global browser */

"use strict";

const METHODS = [${methods}];

browser.runtime.onMessage.addListener((message) => {
  if (
    !message ||
    message.channel !== "${ns}" ||
    !METHODS.includes(message.method)
  ) {
    return undefined;
  }
  return browser.${ns}[message.method](...(message.args ?? []));
});
`;
}

function genContentEntry(a: Actor): string {
  return `// SPDX-License-Identifier: MPL-2.0
// GENERATED by build.ts.
import { content, meta } from "../../${a.dir}/actor.ts";
import { runContent } from "../../_shared/contentRuntime.ts";
runContent(meta, content);
`;
}

// Re-export only `parent` so the parent bundle tree-shakes out the content hook
// (and birpc) — none of that should ship in the main-process module.
function genParentEntry(a: Actor): string {
  return `// SPDX-License-Identifier: MPL-2.0
// GENERATED by build.ts.
export { parent } from "../../${a.dir}/actor.ts";
`;
}

function genJarMn(actors: Actor[]): string {
  const header =
    "noraneko.jar:\n% resource noraneko-builtin %nora-builtin/ contentaccessible=yes";
  const files = actors.flatMap((a) =>
    [
      "manifest.json",
      "schema.json",
      "api.js",
      "background.js",
      "actor.mjs",
      "content.js",
    ].map((f) => `nora-builtin/${a.dir}/${f} (${a.dir}/${f})`),
  );
  files.push("nora-builtin/builtins.json (builtins.json)");
  return `${header}\n ${files.join("\n ")}\n`;
}

async function runTsdown(config: string, actorDir: string): Promise<void> {
  const cmd = new Deno.Command("deno", {
    args: ["run", "-A", "npm:tsdown", "-c", config, `--env.MODE=${mode}`],
    cwd: ROOT,
    env: { WEBEXT_ACTOR: actorDir },
    stdout: "inherit",
    stderr: "inherit",
  });
  const { code } = await cmd.output();
  if (code !== 0) {
    throw new Error(`tsdown failed for ${config} (${actorDir})`);
  }
}

// --- main ---

const actorDirs = discoverActorDirs();
const actors = await Promise.all(actorDirs.map(loadActor));

await Deno.remove(DIST, { recursive: true }).catch(() => {});
await Deno.remove(GEN, { recursive: true }).catch(() => {});

const builtins = [];
for (const a of actors) {
  const outDir = path.join(DIST, a.dir);
  Deno.mkdirSync(outDir, { recursive: true });
  Deno.writeTextFileSync(path.join(outDir, "manifest.json"), genManifest(a));
  Deno.writeTextFileSync(path.join(outDir, "schema.json"), genSchema(a));
  Deno.writeTextFileSync(path.join(outDir, "api.js"), genApi(a));
  Deno.writeTextFileSync(path.join(outDir, "background.js"), genBackground(a));

  const genDir = path.join(GEN, a.dir);
  Deno.mkdirSync(genDir, { recursive: true });
  Deno.writeTextFileSync(
    path.join(genDir, "content.entry.ts"),
    genContentEntry(a),
  );
  Deno.writeTextFileSync(
    path.join(genDir, "parent.entry.ts"),
    genParentEntry(a),
  );

  builtins.push({
    id: a.meta.id,
    version: a.meta.version,
    pref: `noraneko.webext-actors.${a.dir}.enabled`,
    res_url: `resource://noraneko-builtin/${a.dir}/`,
  });
}

Deno.writeTextFileSync(
  path.join(DIST, "builtins.json"),
  JSON.stringify(builtins, null, 2) + "\n",
);
Deno.writeTextFileSync(path.join(DIST, "jar.mn"), genJarMn(actors));
Deno.writeTextFileSync(
  path.join(DIST, "moz.build"),
  `JAR_MANIFESTS += ["jar.mn"]\n`,
);

console.log(
  `[webext-actors] generated ${actors.length} actor(s): ${actorDirs.join(", ")}`,
);

for (const a of actors) {
  await runTsdown("tsdown.actor.config.ts", a.dir);
  await runTsdown("tsdown.content.config.ts", a.dir);
}

console.log("[webext-actors] build complete.");
